added tests for proxy url
redhataccess/cheesecake-api-tests pull request #17
Opened 2021-06-04 12:07 UTC by pbadak

2021-06-07 07:16 UTC, noopurmath3 reviewed
Added 2 comments
Other than that LGTM!

2021-06-07 07:16 UTC, noopurmath3 commented on suites/test_module_content.py
> +PROXIES = {'http': 'http://squid.corp.redhat.com:3128', 'https': 'http://squid.corp.redhat.com:3128'}
This can be read from the config.ini file
It is an existing value

2021-06-07 09:11 UTC, anarang requested changes

2021-06-07 09:11 UTC, anarang commented on suites/test_module_content.py
> +PROXIES = {'http': 'http://squid.corp.redhat.com:3128', 'https': 'http://squid.corp.redhat.com:3128'}
@pbadak please move the proxy config to config.ini, actual values don't go here!

2021-06-07 13:05 UTC, pbadak commented on suites/test_module_content.py
> +  @lcc.test("Verify response of module variant api for pantheon API")
done

2021-06-08 11:41 UTC, noopurmath3 approved these changes
LGTM :+1:

2021-06-08 11:44 UTC, merged