Added changes which are required  when upgraded to python 3.9
redhataccess/cheesecake-api-tests pull request #20
Opened 2021-08-27 14:18 UTC by rutdeshm

2021-08-31 11:01 UTC, anarang reviewed
just ran through the code, added some suggestions there, would let @noopurmath3 and @pbadak do the final review.

2021-09-02 11:21 UTC, rutdeshm commented on suites/test_sitemap.py
> +        #lcc.log_info(xml_dict.items())
@anarang I will un-comment the that line.

2021-09-02 11:22 UTC, rutdeshm commented on suites/test_sitemap.py
> +
@anarang Sure,I will configure pylint with pycharm.

2021-09-02 11:23 UTC, rutdeshm commented on suites/test_sitemap.py
> +        # for sitemap in root:
@anarang ok,will do that

2021-09-02 11:27 UTC, rutdeshm commented on suites/test_sitemap.py
> +        '''
@anarang For commenting out the multiline code I have used that,as per above comment I will remove that code.

2021-09-20 06:17 UTC, noopurmath3 requested changes
@rutdeshm Please remove the .DS_Store file and add it to .gitignore file (I should not be commited)
And please add the config.ini.sample back

2021-09-20 09:28 UTC, noopurmath3 approved these changes
LGTM
However, going forward please try to add a unique message to each commit which summarizes the changes made in that particular commit

2021-10-12 06:49 UTC, merged